name: store_prototype
description: "Aplicación de tienda digital"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get_it: ^8.0.3 # Inyección de Dependencias
  flutter_riverpod: ^2.6.1 # Manejo de Estado con Riverpod
  flutter_svg: ^2.0.17 # Para trabajar con SVGs
  carousel_slider: ^5.0.0 # Para el carrusel de imágenes
  intl: ^0.20.2 # Para formato de fechas y números
  http: ^1.3.0 # Para hacer peticiones HTTP
  json_serializable: ^6.9.4 # Para serializar y deserializar JSON
  rxdart: ^0.28.0 # Para trabajar con Streams
  cached_network_image: ^3.4.1 # Para cachear imágenes
  flutter_secure_storage: ^9.2.4 # Para almacenar información sensible

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Light.ttf
          weight: 300
        - asset: assets/fonts/Quicksand-Regular.ttf
          weight: 400
        - asset: assets/fonts/Quicksand-Medium.ttf
          weight: 500
        - asset: assets/fonts/Quicksand-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700
